# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: DEBIAN11-amd64-DEBs-Builder

env:
  CLOUDSMITH_REPO: "dev"
  RELEASE_VERSION: "1" 
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        EPAS_MAJOR_VERSION: [ 14, 13, 12, 11 ]

    steps:
      - run: echo ${{matrix.EPAS_MAJOR_VERSION}























#name: Java CI with Maven

#on:
 # push:
  #  branches: [ master ]

#jobs:
 # build:

   # runs-on: ubuntu-latest

   # steps:
   # - uses: actions/checkout@v2
   # - name: Set up JDK 11
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '11'
     #   distribution: 'adopt'
      
   # - name: List the current directory
   #   run: ls -a
   
