# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  ICU_VERSION: "66.1-1"
  #ICU_MAJOR_VERSION: echo "${{env.ICU_VERSION}}" | cut -d'.' -f1
  run: echo "ICU_MAJOR_VERSION=$(echo ${{env.ICU_VERSION}} | cut -c 1-6)"
  
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Printing ICU_MAJOR_VERSION value
      run: |
        echo $ICU_MAJOR_VERSION
        echo "${{env.ICU_VERSION}}"

      
      
  
