# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  ICU_VERSION: "66.1-1"
  #ICU_MAJOR_VERSION: echo "${{env.ICU_VERSION}}" | cut -d'.' -f1
  #run: echo "ICU_MAJOR_VERSION=$(echo $ICU_VERSION | cut -c 1-2)" >> $GITHUB_ENV
  
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: ICU_MAJOR_VERSION
      run: echo "ICU_MAJOR_VERSION=$(echo $ICU_VERSION | cut -d'.' -f1)"
    - name: ICU_BUILD_NUMBER
      run: echo "ICU_BUILD_NUMBER=$(echo $ICU_VERSION | cut -d'-' -f2)"
    - name: Printing the values
      run: |
        echo ${{env.ICU_VERSION}}
        echo ${{env.ICU_MAJOR_VERSION}}
        echo ${{env.ICU_BUILD_NUMBER}}
        
      

      
      
  
