# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  ICU_VERSION: "66.1-1"
  #ICU_MAJOR_VERSION: echo "${{env.ICU_VERSION}}" | cut -d'.' -f1
  run: echo "ICU_MAJOR_VERSION=$(echo $ICU_VERSION | cut -d'.' -f1)"
  
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: |
        echo "${{env.ICU_VERSION}}"
        echo "${{env.ICU_MAJOR_VERSION}}"
        
      
    - name: List the current directory
      run: ls -a
      
    - name: List the target folder
      run: |
        cd target
        ls -a
